### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by punkouter2021** [RobertDyball/A2SPA#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0-beta2-0614)' for '.NETCoreApp,Version=v1.1'.				
Error		Unable to resolve 'OpenIddict.Mvc (>= 1.0.0-beta2-0614)' for '.NETCoreApp,Version=v1.1'.				
Error		Unable to resolve 'OpenIddict.Core (>= 1.0.0-beta2-0614)' for '.NETCoreApp,Version=v1.1'.				
Error		Unable to resolve 'OpenIddict (>= 1.0.0-beta2-0614)' for '.NETCoreApp,Version=v1.1'.				
Error	TS2307	Build:Cannot find module '@angular/animations/browser'.	A2SPA	C:\Users\punko\Source\Repos\A2SPA\VS2017\A2SPA\node_modules\@angular\platform-browser\animations\src\animation_renderer.d.ts	1	
Error	TS2307	Build:Cannot find module '@angular/animations/browser'.	A2SPA	C:\Users\punko\Source\Repos\A2SPA\VS2017\A2SPA\node_modules\@angular\platform-browser\animations\src\providers.d.ts	8

**Comment by RobertDyball** [comment]
ouch. Have a look in Visual studio, at your Nuget sources. 
Make sure you have these added:
standard one:
NuGet ... https://api.nuget.org/v3/index.json

new contribs:
aspnet-contrib ....  https://www.myget.org/F/aspnet-contrib/api/v3/index.json

The OpenIdDict and some other early release sources are put on MyGet not NuGet
see here: https://github.com/openiddict/openiddict-core

Just re-looking at the error, make sure you have animations in system.config.js if you are using toasts
your bundles should have 2 extra animations lines:

`            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.min.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
`

Do let me know if you get this resolved or not, (sorry I missed the question too).

**Comment by punkouter2021** [comment]
yes. I needed that myget source. works now
