### ISSUE TITLE
missing type: node, mocha and other things.

### ISSUE THREAD

**Issue by bluewuxi** [RobertDyball/A2SPA#3]
I am using vs2017. When I opened the solution, there were so many errors, such as missing type node/mocha, etc. I tried a couple of days and finally found how to solve them.
Modify **devDependencies** section of  **package.json**
`
  "devDependencies": {
    "tslint": "^5.0.0",
    "chai": "^3.5.0",
    "typings": "^2.1.1",
    "@types/node": "^7.0.21",
    "@types/mocha": "^2.2.41",
    "@types/chai": "*"
  },
`

**Comment by RobertDyball** [comment]
sorry for that; I realised a couple of days ago I'd posted source of a broken build. 
Which branch was it had this issue?
I may have fixed some of them, as I found I had not done a hard reset and there were leftovers in node modules folder that were used, but not part of the solution.

Glad you got it fixed, sorry again for hassles.

**Comment by muniom** [comment]
Master branch seems to still be missing these in package.json FYI

**Comment by Daewl** [comment]
package.json
`{
  "name": "a2spa",
  "version": "1.0.0",
  "description": "ASP.Net Core and Angular 4 Single Page Applicaiton",
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.3.1",
    "@angular/compiler": "^4.3.1",
    "@angular/compiler-cli": "^4.3.1",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.3.1",
    "@angular/http": "^4.3.1",
    "@angular/platform-browser": "^4.3.1",
    "@angular/platform-browser-dynamic": "^4.3.1",
    "@angular/platform-server": "^4.3.1",
    "@angular/router": "^4.3.1",
    "angular-in-memory-web-api": "^0.3.1",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "ionicons": "^3.0.0",
    "mocha": "^3.4.2",
    "ngx-toastr": "^5.0.6",
    "octicons": "^5.0.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.3.0",
    "systemjs": "^0.20.11",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "tslint": "^5.0.0",
    "typescript": "^2.4.2"
  },
  "repository": {},
  "scripts": {
    "test": "mocha"
  }
}
`

on build give me this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error:TS2688	
Build:Cannot find type definition file for 'mocha'.	A2SPA	
	
the problem still persist
